### ISSUE TITLE
ncd-remote question

### ISSUE THREAD

**Issue by JoelGardes** [Orange-OpenSource/documentare-simdoc#85]
Am I right if I suppose that we cannot launch more than one program ncd-remote ?

**Comment by ChristopheMaldivi** [comment]
@JoelGardes yes, since the first step of `ncd-remote` is to kill all current tasks on all machines.

It is convenient right now, but some comments for the future:
 - 'kill-all' could be optional -> this way you could launch several `ncd-remote` at the same time
 - the several instances of `ncd-remote` are concurrents; at some point it will be the time to think at designing a kind of client manager (with priorities, etc). But it is maybe not our job to automate such features (int the simdoc library).

**Comment by JoelGardes** [comment]
@ChristopheMaldivi just note that trying to launch a second session of ncd-remote occurs, the first falls in error.

**Comment by ChristopheMaldivi** [comment]
https://httpstatusdogs.com/426-upgrade-required

**Comment by JoelGardes** [comment]
https://httpstatusdogs.com/429-too-many-requests
